<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'gchart' => $vendorDir . '/gChartPhp/gChartPhp/',
    'TYPO3\\TypoScript' => $baseDir . '/Packages/Application/TYPO3.TypoScript//Classes',
    'TYPO3\\Twitter\\Bootstrap' => $baseDir . '/Packages/Application/TYPO3.Twitter.Bootstrap//Classes',
    'TYPO3\\SwiftMailer' => $baseDir . '/Packages/Application/TYPO3.SwiftMailer//Classes',
    'TYPO3\\Setup' => $baseDir . '/Packages/Application/TYPO3.Setup//Classes',
    'TYPO3\\Party' => $baseDir . '/Packages/Framework/TYPO3.Party//Classes',
    'TYPO3\\Kickstart' => $baseDir . '/Packages/Framework/TYPO3.Kickstart//Classes',
    'TYPO3\\Form' => $baseDir . '/Packages/Application/TYPO3.Form//Classes',
    'TYPO3\\Fluid' => $baseDir . '/Packages/Framework/TYPO3.Fluid//Classes',
    'TYPO3\\Flow' => $baseDir . '/Packages/Framework/TYPO3.Flow//Classes',
    'TYPO3\\Expose' => $baseDir . '/Packages/Application/TYPO3.Expose//Classes',
    'TYPO3\\Eel' => $baseDir . '/Packages/Application/TYPO3.Eel//Classes',
    'Symfony\\Component\\Yaml\\' => $vendorDir . '/symfony/yaml/',
    'Symfony\\Component\\DomCrawler\\' => $vendorDir . '/symfony/dom-crawler/',
    'Symfony\\Component\\Console\\' => $vendorDir . '/symfony/console/',
    'Sandstorm\\Plumber' => $baseDir . '/Packages/Application/Sandstorm.Plumber//Classes',
    'Sandstorm\\PhpProfiler' => $baseDir . '/Packages/Application/Sandstorm.PhpProfiler//Classes',
    'Mrimann\\XliffTranslator' => $baseDir . '/Packages/Application/Mrimann.XliffTranslator//Classes',
    'Famelo\\Scheduler' => $baseDir . '/Packages/Application/Famelo.Scheduler//Classes',
    'Famelo\\Navigation' => $baseDir . '/Packages/Application/Famelo.Navigation//Classes',
    'Famelo\\Gerrit' => $baseDir . '/Packages/Application/Famelo.Gerrit//Classes',
    'Famelo\\ADU' => $baseDir . '/Packages/Application/Famelo.ADU//Classes',
    'Faker' => $vendorDir . '/fzaninotto/faker/src/',
    'Doctrine\\ORM\\' => $vendorDir . '/doctrine/orm/lib/',
    'Doctrine\\DBAL\\Migrations' => $vendorDir . '/doctrine/migrations/lib',
    'Doctrine\\DBAL\\' => $vendorDir . '/doctrine/dbal/lib/',
    'Doctrine\\Common\\Lexer\\' => $vendorDir . '/doctrine/lexer/lib/',
    'Doctrine\\Common\\Inflector\\' => $vendorDir . '/doctrine/inflector/lib/',
    'Doctrine\\Common\\DataFixtures' => $vendorDir . '/doctrine/data-fixtures/lib/',
    'Doctrine\\Common\\Collections\\' => $vendorDir . '/doctrine/collections/lib/',
    'Doctrine\\Common\\Cache\\' => $vendorDir . '/doctrine/cache/lib/',
    'Doctrine\\Common\\Annotations\\' => $vendorDir . '/doctrine/annotations/lib/',
    'Doctrine\\Common\\' => $vendorDir . '/doctrine/common/lib/',
    'Cron' => $vendorDir . '/mtdowling/cron-expression/src/',
    'Composer\\Installers\\' => $vendorDir . '/typo3/flow-composer-installers/src/',
    'Community\\CacheExtensions' => $baseDir . '/Packages/Application/Community.CacheExtensions//Classes',
);
