<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130725133700 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_adu_domain_model_customer DROP FOREIGN KEY FK_3CEBB62A441282A1");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_customer ADD CONSTRAINT FK_3CEBB62A441282A1 FOREIGN KEY (consultant) REFERENCES famelo_adu_domain_model_user (persistence_object_identifier) ON DELETE SET NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_adu_domain_model_customer DROP FOREIGN KEY FK_3CEBB62A441282A1");
		$this->addSql("ALTER TABLE famelo_adu_domain_model_customer ADD CONSTRAINT FK_3CEBB62A441282A1 FOREIGN KEY (consultant) REFERENCES famelo_adu_domain_model_user (persistence_object_identifier)");
	}
}

?>